//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTİTYPROJECTAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATİS
    {
        public int SATISID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> MUSTERİ { get; set; }
        public Nullable<decimal> FİYAT { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
    
        public virtual TBL_MUSTERİ TBL_MUSTERİ { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
